# Generated by Django 4.2.1 on 2023-06-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrosGrupoConexao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_conexao_lider_membros', to='membros.membro')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoConexao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_celula', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='', max_length=1)),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_conexao_lider', to='membros.membro')),
            ],
        ),
    ]
