# Generated by Django 4.2.1 on 2023-06-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ministerio', models.CharField(choices=[('1', 'Pastoral'), ('2', 'Louvor'), ('3', 'Dança'), ('4', 'Atmosfera'), ('5', 'Royal Kids'), ('6', 'Teens'), ('7', 'Fé em Ação')], default='', max_length=2)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='', max_length=1)),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerios', to='membros.membro')),
            ],
        ),
    ]
