# Generated by Django 4.2.1 on 2023-06-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '__first__'),
        ('ministerios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministerio',
            name='membro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='membros.membro'),
        ),
    ]
